/** ********* mutations ***********/

// user
export const FETCH_USER_SUC = 'FETCH_USER_SUC'

// same
export const FETCH_SAMELIST_SUC = 'FETCH_SAMELIST_SUC'
export const FETCH_CHANNELSAMELIST_SUC = 'FETCH_CHANNELSAMELIST_SUC'
export const FETCH_CHANNELLIST_SUC = 'FETCH_CHANNELLIST_SUC'
export const FETCH_QUERY_CHANNELLIST_SUC = 'FETCH_QUERY_CHANNELLIST_SUC'
export const FETCH_HOT_CHANNELLIST_SUC = 'FETCH_HOT_CHANNELLIST_SUC'
export const DIANZAN_USER_SUC = 'DIANZAN_USER_SUC'
export const FETCH_USER_SENSE_SUC = 'FETCH_USER_SENSE_SUC'

// 聊天功能
export const FETCH_USERCHATLIST_SUC = 'FETCH_USERCHATLIST_SUC'
export const PUT_USER_CHAT_SUC = 'PUT_USER_CHAT_SUC'
export const FETCH_USER_INFO_SUC = 'FETCH_USER_INFO_SUC'
export const FETCH_USER_INFO2_SUC = 'FETCH_USER_INFO2_SUC'
export const FETCH_UNREAD_MESSAGE_SUC = 'FETCH_UNREAD_MESSAGE_SUC'
